bottom navigation view
falconArdente/diploma-team_4-koh_11-practicum-android pull request #18
Opened 2024-07-07 19:48 UTC by akimoxy

Добавила bottom navigation view
Реализовала его видимость в фрагментах

2024-07-07 20:30 UTC, falconArdente requested changes

2024-07-07 20:30 UTC, falconArdente commented on app/src/main/res/layout/activity_root.xml
> +        android:layout_height="58dp"
Предлагаю вынести в ресурсы и по-моему там 56dp, в top-line та же тема про hardcode

2024-07-08 09:19 UTC, akimoxy commented on app/src/main/res/layout/activity_root.xml
> +        android:layout_height="58dp"
![111](https://github.com/falconArdente/diploma-team_4-koh_11-practicum-android/assets/140650681/30f1ced8-7616-49d5-ac6a-c50099e65ead)

там 57,округлила до 58

2024-07-08 09:21 UTC, akimoxy commented on app/src/main/res/layout/activity_root.xml
> +        android:layout_height="58dp"
Хотя сейчас один айтем выделила и показал 56))Давай на 56 исправлю

2024-07-08 10:16 UTC, falconArdente approved these changes

2024-07-08 10:46 UTC, merged