Верстка экрана Поиск
falconArdente/diploma-team_4-koh_11-practicum-android pull request #45
Opened 2024-07-11 14:06 UTC by ralvveo

Сверстан экран Поиска, реализовано правильное поведение поля ввода текста

2024-07-11 16:43 UTC, ZimikXXIV requested changes

2024-07-11 16:43 UTC, ZimikXXIV commented on app/src/main/res/values/colors.xml
> +    <color name="Light_Gray_Gray">#E6E8EB</color>
Зачем повторяющиеся цвета? Они уже есть в "палитре"

2024-07-11 16:43 UTC, ZimikXXIV commented on app/src/main/res/layout/fragment_search_job.xml
> +        android:layout_marginStart="16dp"
16dp лучше вынести в ресурсы, насчет 0dp не уверен, но тоже вынес бы

2024-07-11 16:43 UTC, ZimikXXIV commented on app/src/main/res/layout/fragment_search_job.xml
> +        android:layout_marginTop="4dp"
Размеры вроде c dp лучше вынести в ресурсы

2024-07-11 22:58 UTC, falconArdente requested changes

2024-07-11 22:58 UTC, falconArdente commented on app/src/main/res/layout/fragment_search_job.xml
> +    <EditText
Я не нашел присвоения цвета курсора ни в стиле ни в layout. Ожидаемый цвет:Blue.

2024-07-11 22:58 UTC, falconArdente commented on app/src/main/res/values-night/colors.xml
> +    <color name="Light_Gray_OR_Gray">@color/Light_Gray</color>
По-моему Gray ночью, нет?

2024-07-11 22:58 UTC, falconArdente commented on app/src/main/res/layout/fragment_search_job.xml
> +        android:layout_marginTop="@dimen/dp4"
Похоже, здесь 11
![Без имени-1](https://github.com/user-attachments/assets/009cf7d9-96ad-4ec5-bf04-7e13fa46ee1c)

2024-07-12 16:10 UTC, ralvveo commented on app/src/main/res/values-night/colors.xml
> +    <color name="Light_Gray_OR_Gray">@color/Light_Gray</color>
ну да, днем светло-серый, ночью серый

2024-07-12 16:11 UTC, ralvveo commented on app/src/main/res/layout/fragment_search_job.xml
> +        android:layout_marginTop="@dimen/dp4"
ой, да, там должно быть 12(округлял), поправил

2024-07-12 17:06 UTC, falconArdente commented on app/src/main/res/values-night/colors.xml
> +    <color name="Light_Gray_OR_Gray">@color/Light_Gray</color>
А стоит светло серый

2024-07-12 17:07 UTC, falconArdente approved these changes

2024-07-12 18:15 UTC, merged