add Interactor, 2 models in domain, converter
falconArdente/diploma-team_4-koh_11-practicum-android pull request #47
Opened 2024-07-11 14:10 UTC by akimoxy

Добавила интерактор и его реализацию
Две модельки в домэйн
Конвертер

2024-07-11 16:35 UTC, ZimikXXIV commented on app/src/main/java/ru/practicum/android/diploma/search/domain/api/SearchInteractor.kt
> +    fun searchVacation(expression: String): Flow<Pair<VacancyModelResponce?, String?>>
Чтобы не тянуть такие страшные конструкции предлагаю использовать какую-ниюудь структуру, их разряда State у экранов(интерфейс с дата классами), у которой есть или Data или Error, ну или как удобно тут

2024-07-11 16:36 UTC, ZimikXXIV commented on app/src/main/java/ru/practicum/android/diploma/search/data/repository/SearchInteractorImpl.kt
> +                    Pair(converter.mapToVacancyModelResponce(result.data!!), null)
ну и собственно тот тоже передавать этот же интерфейс с дата классами

2024-07-12 00:07 UTC, falconArdente requested changes

2024-07-12 00:07 UTC, falconArdente commented on app/src/main/java/ru/practicum/android/diploma/search/domain/model/VacancyModelResponce.kt
> +class VacancyModelResponce(
VacancyModelResponce тут я определенно душню: responSe

2024-07-12 00:07 UTC, falconArdente commented on app/src/main/java/ru/practicum/android/diploma/search/data/repository/SearchInteractorImpl.kt
> +import ru.practicum.android.diploma.search.domain.model.VacancyModelResponce as VacancyModelResponce1
import ru.practicum.android.diploma.search.domain.model.VacancyModelResponce **as VacancyModelResponce1**
...
 override fun searchVacation(expression: String): Flow<Pair<VacancyModelResponce**1**?, String?>> = flow {

Это Android Studio попытался развести тебя на псевдоним с единицой в оканчании " VacancyModelResponce1"
можно удалить: "as VacancyModelResponce1" и единицу в "override fun searchVacation(expression: String): Flow<Pair<VacancyModelResponce1"

2024-07-12 00:26 UTC, falconArdente commented on app/src/main/java/ru/practicum/android/diploma/search/data/repository/SearchVacancyConverter.kt
Возможно есть смысл положить его в search/data/mapper пакет

2024-07-12 00:38 UTC, falconArdente commented on app/src/main/java/ru/practicum/android/diploma/search/data/repository/SearchInteractorImpl.kt
> +                is Resource.Success -> {
Я правильно понимаю, что мы здесь конвертим DTO-объект в такой же DTO-объект? Может стоит сразу в эталонный Vacancy из модели конвертить?
![Без имени-2](https://github.com/user-attachments/assets/6973e67e-6f81-4b1d-8289-b5c576bf7881)

2024-07-13 16:43 UTC, falconArdente approved these changes
Все верно разложено по архитекутре. Скорее всего понадобится поправить конверсию классов, ты спокойно можешь сделать это на последующих задачах

2024-07-13 16:43 UTC, falconArdente commented on app/src/main/java/ru/practicum/android/diploma/search/data/repository/SearchInteractorImpl.kt
> +class SearchInteractorImpl(val repository: SearchRepository, val converter: SearchVacancyConverter) : SearchInteractor {
Здесь в будующем скорее всего придется еще дорабатывать конверси вложенных объектов, типа AreaModel, PhoneModel, SalaryModel и так далее

2024-07-13 17:13 UTC, merged