37 отец мини фильтров
falconArdente/diploma-team_4-koh_11-practicum-android pull request #95
Opened 2024-07-19 16:26 UTC by akimoxy

Создала xml для фрагментов отрасли,страны,региона

2024-07-19 20:35 UTC, Spyker3D approved these changes

2024-07-19 20:35 UTC, Spyker3D commented on app/src/main/res/layout/fragment_filter_with_recycler.xml
> +        android:layout_marginTop="@dimen/dp16"
На макете вроде бы побольше отступ View от заголовка - вроде как 28dp, если округлить. Или отступ поменьше, чтобы все элементы влезли необрезанными? Не знаю насколько ревьюер строго к отступам относится, на всякий случай указал )

2024-07-19 20:35 UTC, Spyker3D commented on app/src/main/res/layout/fragment_filter_with_recycler.xml
> +        android:layout_marginTop="@dimen/dp16"
У меня по макету получается около 30dp расстояние от поля поиска до текстового элемента RecyclerView, по верстке получает 22dp, хотя может и не критично )

2024-07-19 22:12 UTC, falconArdente requested changes
Меня взволновало поле автозавершения текста

2024-07-19 22:12 UTC, falconArdente commented on app/src/main/res/drawable/switch_onn.xml
Можно убрать вторую n в названии через shift+F6, но я не настаиваю, просто мысли в слух.

2024-07-20 10:25 UTC, falconArdente approved these changes

2024-07-20 10:34 UTC, merged